### ISSUE TITLE
Panic when a transaction has payments into more than one account tracked by sqlite

### ISSUE THREAD

**Issue by AArnott** [zcash/librustzcash#1282]
The latest librustzcash in main, with the orchard feature enabled, panics during account recovery for me, on this line: https://github.com/zcash/librustzcash/blob/e0227ed175d8e1c6d1aaffb2e69ba930069a4c10/zcash_client_sqlite/src/lib.rs#L1047

When adding a transaction to the sqlite database, if the tx has multiple outputs, destined for more than one account that is tracked by the sqlite database, a panic results.

Panic text:
> This isn't a z->t spend at least because we're in orchard (not sapling).

I also don't see anything suggesting this is an unshielding transaction. We're just looping over orchard outputs here.
Why is the local variable called `spending_account_id` when in fact it is set to the value of the _receiving_ account id?
And why must every output in a transaction have the same receiving account? This looks like a panic will occur for any transaction that sends outputs to more than one account tracked by the sqlite db. 
And in fact, I found this code due to a panic when doing account recovery for a testnet account I have, and a multi-account transaction is very likely to be what I have here (though I haven't confirmed this.)
See also [discord post](https://discord.com/channels/809218587167293450/876655911790321684/1219086198513860659).

_Originally posted by @AArnott in https://github.com/zcash/librustzcash/pull/1234#discussion_r1527664053_

**Comment by nuttycom** [comment]
The code that causes this problem was originally introduced in 665c4c7aff3743fce38e7527b553197c51ffa65e in 2021, very early on in the development of this code. I think that the original rationale was perhaps related to the fact that when using decrypted transaction data, we can only consistently obtain the account ID for incoming transactions. Since there was only ever one account in the wallet, the incoming and outgoing account were assumed to be the same; that assumption was broken when we later added the ability to create additional accounts, but we never ran into it (because the mobile wallets still only use a single account.)

What needs to be done to resolve this is to determine the sending account by checking against the nullifiers of the notes that were spent instead.

**Comment by nuttycom** [comment]
Fixed by #1306
