### ISSUE TITLE
`create_proposed_transactions` can incorrectly produce transactions

### ISSUE THREAD

**Issue by str4d** [zcash/librustzcash#1463]
https://github.com/zcash/librustzcash/blob/4f95bd22d47f6997a3dd5017c01c40769cdab3db/zcash_client_backend/src/data_api/wallet.rs#L611-L646

We are looping over the proposal steps, and calling `create_proposed_transaction` for each step. Then we check whether any ephemeral outputs were created but not spent, and return an error.

The bug is, this is not done transactionally. `create_proposed_transaction` alters the wallet:
https://github.com/zcash/librustzcash/blob/4f95bd22d47f6997a3dd5017c01c40769cdab3db/zcash_client_backend/src/data_api/wallet.rs#L1281-L1294

If the caller is separately scanning the wallet for unmined transactions to resubmit, it will see those created transactions, and "resubmit" them bypassing the intended error state.

It is currently necessary to add the earlier transactions to the wallet, in order to make their outputs selectable by the next step. We therefore need to either enter a database transaction for this entire call, or we need to manually remove the inserted transactions (and any of their effects).

**Comment by daira** [comment]
We should do the whole thing in a database transaction; that's what they're for.

**Comment by daira** [comment]
Oh, but when I try to implement that I immediately run into the problem that `SqlTransaction` is a `zcash_client_sqlite`-level abstraction, and `create_proposed_transactions` is in `zcash_client_backend`. Indeed a storage layer may have no concept of database transactions.

**Comment by daira** [comment]
> It is currently necessary to add the earlier transactions to the wallet, in order to make their outputs selectable by the next step.

This is the point at which to break the impasse, I think. We should not require the first transaction to have been added to the wallet in order to make its ephemeral output selectable. If that can be made to work, we can create all the transactions first, and then call `wallet_db.store_sent_tx` for them. (This is still not entirely transactional, because `reserve_next_n_ephemeral_addresses` reserves the addresses irrevocably regardless of any subsequent failure. But I knew about that issue and the rest of the ZIP 320 code was written to tolerate it; it doesn't cause any problem with resubmissions.)

**Comment by nuttycom** [comment]
It should be sufficient to collect the transactions in a vector, and then submit them all at once, I agree.
