### ISSUE TITLE
zcash_client_backend: Replace `scan_progress` result with a struct that includes both scan and recovery progress.

### ISSUE THREAD

**Issue by nuttycom** [zcash/librustzcash#1559]
In https://github.com/zcash/librustzcash/pull/1541, the semantics of `WalletRead::scan_progress` were quietly changed so that this method now returns only the progress since the wallet's recovery height, rather than all wallet scan and recovery progress as it had previously done. Since this is not a breaking API change, it can potentially be missed by an incautious user of the API; as such, we should make an API-breaking change to remedy this potential footgun. Either the `scan_progress` method should be renamed, or the `recovery_progress` method could be removed and the `scan_progress` result type could be replaced by a struct that contains the progress information for both before and after the wallet's recovery height.

**Comment by str4d** [comment]
I don't consider this a "footgun" in the normal sense of the word. If a downstream user upgrades from 0.13 to 0.14 (which is inherently a breaking change upgrade, and _always_ requires care from the downstream user), and does not read the changelog (which clearly documented the change):

https://github.com/zcash/librustzcash/blob/dec3024b0da78d1dcb9c6b84bc44e829748f66a5/zcash_client_backend/CHANGELOG.md?plain=1#L48-L51

then the effect on their code or app is that:
- For recovered-from-seed wallets where their code sets the recovery height, then _during initial recovery_ the scan percentage will go from 0 to 100% "quickly" and then sit at 100% while the wallet is actually scanning. There is no risk of loss of funds (because anything that hasn't been recovered yet simply won't be visible to the user). The only issue is user confusion, and the fix is trivial (aggregate the scan and recovery percentages in the interim, then expose them both).
- For recovered-from-seed wallets that had previously been fully synced (i.e. an app update), the scan percentage will be more responsive than before, and still cover all scanning progress.
- For new wallets, or recovered-from-seed wallets where their code _does not_ set the recovery height, the scan percentage will be identical to before (actually slightly better, as we fixed the chain tip progress estimation).

**Comment by nuttycom** [comment]
Completed in #1562
