### ISSUE TITLE
Attempt to decrypt outputs while scanning blocks

### ISSUE THREAD

**Issue by gmale** [zcash/librustzcash#156]
## Request
As a wallet developer, I'd like to fully restore a wallet from a backup, including outbound transactions so that all transaction data can be derived from the blockchain, using a seed, alone.

## Issue
Currently, only inbound transactions are decrypted which means outbound transactions will not show up in a wallet that is restored from a seed, alone.

## Implementation Notes
We could use an approach similar to zecwallet-light, which leverages `try_sapling_output_recovery` during the scan process:
https://github.com/adityapk00/zecwallet-light-cli/blob/master/lib/src/lightwallet.rs#L1014-L1069

**Comment by str4d** [comment]
When discussing this with @gmale, I forgot that the current CompactBlock format drops the `outCiphertext`, which is needed to perform this recovery. This means that we can't do shielded output detection during regular chain scanning, and instead need to perform it once we have the full transaction (which indeed appears to be what Zecwallet Light is doing, at the same time as recovering the memo fields). This still results in us finding all available information (because any transaction we are able to recover an output for, we will also have spent notes in and will detect during chain scanning), but it requires the full transaction-fetching solution.

**Comment by gmale** [comment]
Note for later:
Privately retrieving transaction details "needs research"

One approach might be to find all the blocks where we need transactions and then download random windows around those blocks. For each block in the window, download all its transactions.

**Comment by gmale** [comment]
This has been implemented in librustzcash and incorporated into the wallet apps as part of the memo feature and is complete.
