### ISSUE TITLE
CI: target all officially supported zcashd platforms.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/librustzcash#199]
Glancing at `.github/workflows/ci.yml` it appears we don't target the (older) debian platforms that `zcashd` targets. Let's add those test targets to this CI so we can catch any platform specific issues quickly (and in this nicer/newer CI versus zcashd's older klunkier CI).

**Comment by nathan-at-least** [comment]
Looks like github doesn't provide the target distributions that zcashd uses out-of-the-box. The platforms github provides, according to [Supported Runners and Hardware Resources](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/virtual-environments-for-github-hosted-runners#supported-runners-and-hardware-resources), include:

- Windows Server 2019 aka `windows-latest`
- Ubuntu 18.04 aka `ubuntu-latest` or `ubuntu-18.04`
- Ubuntu 16.04 aka `ubuntu-16.04`
- macOS Catalina 10.15 aka `macos-latest`

Meanwhile, `zcashd` has these [supported builders](https://ci.z.cash/#/builders?tags=%2Bsupported):

- `debian8-k8s-big`
- `debian9-k8s-big`
- `ubuntu1604-k8s-big`
- `ubuntu1804-k8s-big`

So to fulfill this ticket it seems like we'll need custom deployments to the Actions backend, or for `zcashd` to drop `debian` platforms as supported.

**Comment by str4d** [comment]
Targeting the full suite of `zcashd` platforms is much less of a concern for the Rust stack, because we don't have the same kinds of concerns around compatibility with shells, libraries etc. The supported way to build the Rust stack requires installing Rust, and doing that covers all the platform-level compatibility.

The CI workflow here is instead focused on testing against Rust targets, which corresponds to common architectures across the `zcashd` platforms. Testing against `[ubuntu-latest, windows-latest, macOS-latest]` is in reality testing against `[x86_64-linux, x86_64-windows, x86_64-darwin]`. So (for instance) we should also test against `arm64-linux`, but I don't see any value in testing the on Debian vs Ubuntu here.

**Comment by zancas** [comment]
It was partially because of the limited menu of platforms available as backends for github actions that I ended up preferring gitlab for CI.
