### ISSUE TITLE
Cannot create transaction to t-address with no change output

### ISSUE THREAD

**Issue by michaeltout** [zcash/librustzcash#356]
The function ```create_spend_to_address``` in ```zcash_client_backend/src/data_api/wallet.rs``` fails with ```Output 0 should exist in the transaction``` if you attempt to use it to create a spend to a t-address, and set the spend amount to exactly ```balance - DEFAULT_FEE```. 

I suspect this has to do with the fact that ```add_transparent_output``` in ```zcash_primitives/src/transaction/builder.rs``` adds a TxOut value to ```self.mtx.vout``` whereas the public ```build``` function only looks for outputs in the ```self.outputs``` vector, and if no change output is generated, ```self.outputs``` is empty.

Here is a test that you can add to the tests in ```zcash_client_sqlite/src/wallet/transact.rs``` to reproduce the problem, it currently fails for me on your main branch:

```
    use zcash_client_backend::{address::RecipientAddress};

    #[test]
    fn create_to_address_succeeds_to_t_addr_zero_change() {
        let cache_file = NamedTempFile::new().unwrap();
        let db_cache = BlockDB(Connection::open(cache_file.path()).unwrap());
        init_cache_database(&db_cache).unwrap();

        let data_file = NamedTempFile::new().unwrap();
        let db_data = WalletDB::for_path(data_file.path(), tests::network()).unwrap();
        init_wallet_db(&db_data).unwrap();

        // Add an account to the wallet
        let extsk = ExtendedSpendingKey::master(&[]);
        let extfvk = ExtendedFullViewingKey::from(&extsk);
        init_accounts_table(&db_data, &[extfvk.clone()]).unwrap();

        // Add funds to the wallet in a single note
        let value = Amount::from_u64(51000).unwrap();
        let (cb, _) = fake_compact_block(
            sapling_activation_height(),
            BlockHash([0; 32]),
            extfvk.clone(),
            value,
        );
        insert_into_cache(&db_cache, &cb);
        let mut db_write = db_data.get_update_ops().unwrap();
        scan_cached_blocks(&tests::network(), &db_cache, &mut db_write, None).unwrap();

        // Verified balance matches total balance
        let (_, anchor_height) = (&db_data).get_target_and_anchor_heights().unwrap().unwrap();
        assert_eq!(get_balance(&db_data, AccountId(0)).unwrap(), value);
        assert_eq!(
            get_balance_at(&db_data, AccountId(0), anchor_height).unwrap(),
            value
        );

        let to = RecipientAddress::decode(&TEST_NETWORK, "tmA4rvdJU3HZ4ZUzZSjEUg7wbf1unbDBvGb").unwrap();
        create_spend_to_address(
            &mut db_write,
            &tests::network(),
            test_prover(),
            AccountId(0),
            &extsk,
            &to,
            Amount::from_u64(50000).unwrap(),
            None,
            OvkPolicy::Sender,
        )
        .unwrap();
    }
```

**Comment by str4d** [comment]
The underlying issue here is that when `create_spend_to_address()` was originally implemented, it was only intended to be used for spending to a Sapling address, and made assumptions about doing so. However, its API accepted a string, and the underlying parser was later extended to support spending to transparent addresses, without handling the Sapling-specific edge cases.

Specifically, the cause is the interaction of these two sections of code:

https://github.com/zcash/librustzcash/blob/3a8e72936f7d05d26db12172418e5e832cfc48de/zcash_client_backend/src/data_api/wallet.rs#L218-L225

https://github.com/zcash/librustzcash/blob/3a8e72936f7d05d26db12172418e5e832cfc48de/zcash_client_backend/src/data_api/wallet.rs#L232-L236

When creating a `z -> t` transaction, `builder.add_sapling_output()` is not called by `create_spend_to_address()`, breaking the subsequent assumption. For a transaction without change, this will reliably trigger a panic.

For a transaction that has change, this happens to work half the time:
- The transaction builder internally adds a Sapling output for the change.
- The requested zeroth output index will map to a shuffled index of zero 50% of the time, and since there is only one transparent output, it will be at index zero.

I therefore believe this is also the cause of some spurious failures that other users have been seeing for `z -> t` transactions; each retry would have a 50% chance of success, so users probably put it down to transient failures (especially because the mobile SDKs catch panics to prevent them unwinding across the FFI, turning them into internal errors that might just be caught).
