### ISSUE TITLE
Missing tests?

### ISSUE THREAD

**Issue by mirkoAlic** [zcash/librustzcash#49]
I'm trying to do a JNR wrapper of the library, and i can't find unit tests for methods like: `librustzcash_sapling_check_spend`, `librustzcash_sapling_binding_sig`, etc. It is in your future plans to add them?

**Comment by str4d** [comment]
Eventually yes. These various methods are FFIs intended for consumption by `zcashd`, so currently tests of them tend to be in the `zcashd` codebase. What we intend to do as part of #41 is refactor the logic out of the FFI functions to create a pure-Rust API, which can be tested on its own.

The particular methods you refer to have now been refactored into the `zcash_proofs` crate in #30. The next step would be writing tests for them, which will require adding a test params harness (since the test runner may not have the production parameters available). I'll open new issues for this and similar components.

**Comment by str4d** [comment]
I've opened #56 and #57 covering the two parts of this question.
