### ISSUE TITLE
Select the most-preferred shielded receiver in `shield_transparent_funds`

### ISSUE THREAD

**Issue by nuttycom** [zcash/librustzcash#617]
Have this formally select the most preferred shielded receiver. Currently that is Sapling because we can't receive or spend Orchard funds, but that will change soon and we want to remember to update this.

_Originally posted by @str4d in https://github.com/zcash/librustzcash/pull/615#discussion_r956463037_

**Comment by str4d** [comment]
We should check whether this was done; it should be a trivial change. We should also add a test for this, if we don't already have one.

**Comment by str4d** [comment]
The code that was being referenced by this issue was removed in #761, as part of merging the transaction creation parts of `spend` and `shield_transparent_funds`. The relevant code in `create_proposed_transaction` was then generalised with Orchard support, and the preference logic now lives in the `ChangeStrategy` implementation.

For ZIP 317 and shielding transactions specifically, the explicit flows are all transparent (from the transparent inputs), so the shielded receiver is defined by `fallback_change_pool`:
https://github.com/zcash/librustzcash/blob/7f7b685b99132505a0fe4ba588f329e3516e9669/zcash_client_backend/src/fees/zip317.rs#L34-L44
https://github.com/zcash/librustzcash/blob/7f7b685b99132505a0fe4ba588f329e3516e9669/zcash_client_backend/src/fees/common.rs#L114-L142

It is therefore up to the caller to specify where the funds should go. In both the Android and iOS SDKs, this is explicitly set to Orchard, matching the most-preferred logic:
https://github.com/Electric-Coin-Company/zcash-android-wallet-sdk/blob/5bca00a1a4092d35201a2fb7eff14374e1839b88/backend-lib/src/main/rust/lib.rs#L1569
https://github.com/Electric-Coin-Company/zcash-light-client-ffi/blob/679da4c85b3c676a207c5cde6cec25bd4e0d17c4/rust/src/lib.rs#L2771

I therefore think we can close this as completed.

**Comment by daira** [comment]
Closing per @nuttycom's comment.
