### ISSUE TITLE
Add feature flag to toggle between mainnet and testnet

### ISSUE THREAD

**Issue by gtank** [zcash/librustzcash#71]
Instead of requiring all APIs to contain parameter fields, we can leverage the Rust features system to have this handled at build time. The will be a feature on the `zcash_client_backend` crate and possibly on other crates depending on what makes sense.

**Comment by str4d** [comment]
Update: After some refactoring of my light client backend branch, it now seems to make sense for `zcash_client_backend` to be both network-agnostic and client-agnostic, and provide constants for both networks. In particular, this avoids over-constraining that crate (which would prevent downstream forks from using it), while also enabling each API it contains to only have parameters for the specific constants they require (instead of global parameters). The new `zcash_client_sqlite` crate is where the `mainnet` feature is implemented.
