### ISSUE TITLE
Plans for pairing and crates.io?

### ISSUE THREAD

**Issue by afck** [zcash/librustzcash#76]
There are [several projects](https://github.com/filecoin-project/research/issues/53) that use [pairing](https://github.com/zkcrypto/pairing) and would like to contribute to it. They will probably start collaborating on a fork, but I think everyone would also be happy to contribute upstream instead.

Will the librustzcash changes be merged back into the pairing repo eventually, or is that deprecated? Will the new version be published on crates.io?

Would you be open to merging the functionality mentioned in that issue? (Most of the pairing users' feature requests seem to overlap a lot.)
Or is it better for POA, Filecoin, MaidSafe and others to work on a separate fork for now?

**Comment by str4d** [comment]
Yes, the intention is to merge all the changes from this repository back up into the original repositories, as their refactoring in #41 completes. We created Git subtrees in this repository primarily because the refactor requires changing all the crates in parallel, and it is much easier to do this in a single workspace.

We also want to be publishing crates even while the primary development is happening here. The main blocker on that is the fact that we depend on a GitHub repository for BLAKE2b. Once https://github.com/RustCrypto/hashes/pull/78 is merged and released, we can replace this dependency and start publishing crates again 🙂

**Comment by str4d** [comment]
To answer your last question:

- rand update is planned already in #60 and I want to do this soon.
- Hashing to the curve is something I'd like to see an API included for in pairing, but an implementation would likely not go into pairing itself, but into curve-specific crates like bls12_381.
- Serde support: seems reasonable but we'd probably want to merge something later on, as we couldn't promise compatibility across the refactor.

**Comment by afck** [comment]
Thank you for the detailed answer! I guess it's best to keep the Filecoin fork separate for now, and backport the changes after the refactoring is done.
