### ISSUE TITLE
Please provide official binaries !

### ISSUE THREAD

**Issue by ytrezq** [zcash/librustzcash#77]
There are official Zcash binaries which seem to implies there are official librustzcash binaries but they are statically linked.

Compilers versions and flags play a great role in security for rust. Please let testing the library itself !

**Comment by str4d** [comment]
The `librustzcash` library is not currently intended for use as a standalone API outside of `zcashd`, and is not an officially-supported product outside of `zcashd`. This is in part because the current `librustzcash` API is highly specific to `zcashd`'s needs, whereas something that could be supported standalone - particularly as a C FFI, with associated ABI concerns - should have a more broadly-considered API. This might change after the refactor, but there's a bunch of work to do there first.

If you want to test the library as-used in `zcashd`, you can obtain it from the `depends/x86_64-unknown-linux-gnu/lib/librustzcash.a` after building Zcash. Information about how it is built is contained in https://github.com/zcash/zcash/tree/master/depends/packages and https://github.com/zcash/zcash/tree/master/depends/patches/librustzcash. In particular:

- We currently build with Rust 1.32.0.
- Crates versions are all pinned (see both the `Cargo.lock` in this repository (at the version used by `zcashd`), and the `crate_*.mk` files in the Zcash repository).

**Comment by str4d** [comment]
The first version of the Rust crates in this repo that are officially supported have now been released on https://crates.io. It's also likely that at some point the `librustzcash` crate will move from here into the `zcashd` repository, better indicating that it is part of `zcashd` and not a standalone library.
