### ISSUE TITLE
Exception fetching memos for received transactions

### ISSUE THREAD

**Issue by ccjernigan** [zcash/librustzcash#834]
Fetching memos for received transactions fails with an exception, while fetching memos for sent transactions succeeds.  This can be reproduced in the demo app of in Android SDK.  It reproduces with zcash_client_sqlite 0.5 and 0.7.

```
Process: cash.z.ecc.android.sdk.demoapp.testnet, PID: 4890
java.lang.RuntimeException: An error occurred retrieving the memo, Invalid column type Null at index: 0, name: memo
	at cash.z.ecc.android.sdk.jni.RustBackend.getReceivedMemoAsUtf8(Native Method)
	at cash.z.ecc.android.sdk.jni.RustBackend.access$getReceivedMemoAsUtf8(RustBackend.kt:19)
	at cash.z.ecc.android.sdk.jni.RustBackend$Companion.getReceivedMemoAsUtf8(Unknown Source:0)
	at cash.z.ecc.android.sdk.jni.RustBackend$Companion.access$getReceivedMemoAsUtf8(RustBackend.kt:388)
	at cash.z.ecc.android.sdk.jni.RustBackend$getReceivedMemoAsUtf8$2.invokeSuspend(RustBackend.kt:165)
```

**Comment by str4d** [comment]
The core issue here is (most likely, I have not reproduced this yet) that the `memo` column in the `sapling_received_notes` table is `NULL` for the `id_note` being requested. `NULL` doesn't have the same type as `BLOB` (yay SQLite), so we get an error trying to convert it to `Vec<u8>`. So it is correct to get an error in this situation (because there is no memo to fetch), it is just a more obscure error than necessary.

The underlying issue might be that the enhancement logic being performed by the Android SDK is being applied to the sent notes table, but not fully to the received notes table in the case of change notes. We recently changed the wallet DB to store change notes in both tables as a form of double-entry accounting; if the notes returning this error are all change notes, that might be the cause.

**Comment by HonzaR** [comment]
@str4d From my latest testing, this (or something similar) also seems related to the sent transactions. I get `java.lang.RuntimeException: An error occurred retrieving the memo, Query returned no rows` when calling `getSentMemoAsUtf8(idNote: Long)` from the Android SDK.

**Comment by HonzaR** [comment]
The **received** `getMemo` rust API works for me. It replies with a memo in case the transaction contains one or with `RuntimeException`  in case it contains no memo. The **sent** `getMemo` API, on the other hand, always replies with the error above.

**Comment by HonzaR** [comment]
I use our Demo-app and send funds from a sapling to another sapling address. See reproducing steps in the Android SDK repo https://github.com/zcash/zcash-android-wallet-sdk/issues/1154.
