### ISSUE TITLE
Sending "max amount - 1" transaction fails because of insufficient funds

### ISSUE THREAD

**Issue by pacu** [zcash/librustzcash#835]
I’m working on fixing a balance test called testMaxAmountMinusOneSend

I believe I might have found some bug in librustzcash around creating transactions.

https://github.com/zcash/ZcashLightClientKit/blob/main/Tests/DarksideTests/BalanceTests.swift

Why the test is failing:

sendToAddress failed: rustCreateToAddress("Error while sending funds: Insufficient balance (have 200000, need 200999 including fee)

verified balance at the moment of creating tx: 200,000

value being sent: 198_999

fee value on transaction: 1000

result on wiggling the test:

value sent is calculated this way:
let maxBalanceMinusOne = verifiedBalance - Zatoshi(1000) - Zatoshi(1)

if I subtract 1000 zatoshi more
let maxBalanceMinusOne = verifiedBalance - Zatoshi(2000) - Zatoshi(1)

the sentToAddress call won’t fail.

The fee will still be 1000 zatoshi.

And then the test will fail because the expected verified value after 10 confirmations later is not 1 but 1001. Meaning that there’s a bug on the code that asserts the sufficient balance in rust.

**Comment by nuttycom** [comment]
If I understand correctly, this is working as designed. The change creation logic prevents the creation of dust notes. We've discussed the possibility of, in circumstances like this, allowing the dust to be sent to the fee amount, but that opens up a vector for dusting attacks where an adversary could send the victim notes with identifiable dust amounts that they would then watch being exposed in fees in order to detect when those notes are spent.

**Comment by pacu** [comment]
I was not aware of this. Probably the friction should be address by Fee estimation APIs.
