### ISSUE TITLE
Send fails: Tree does not contain a root at address

### ISSUE THREAD

**Issue by HonzaR** [zcash/librustzcash#898]
In the Android SDK, which is operating upon the new SbS sync and the sync is in progress, we can reproduce `RuntimeException: Error while creating transaction: An error occurred in querying or updating a note commitment tree: Tree does not contain a root at address Address { level: Level(0), index: 127765 }`, which comes from the Rust layer of the SDK.

Full log:
```
TransactionEncoderImpl.createSpend(): creating transaction to spend Zatoshi(value=50) zatoshi to ****rgd9 with memo: test send
SaplingParamTool.validate$zcash_android_sdk_1_20_0_beta01_release(): Param files  both exist!
TransactionEncoderImpl.createSpend(): params exist! attempting to send...
TransactionEncoderImpl.createSpend(): Caught exception while creating transaction.
java.lang.RuntimeException: Error while creating transaction: An error occurred in querying or updating a note commitment tree: Tree does not contain a root at address Address { level: Level(0), index: 127765 }
	at cash.z.ecc.android.sdk.internal.jni.RustBackend.createToAddress(Native Method)
	at cash.z.ecc.android.sdk.internal.jni.RustBackend.access$createToAddress(RustBackend.kt:19)
	at cash.z.ecc.android.sdk.internal.jni.RustBackend$Companion.createToAddress(Unknown Source:0)
	at cash.z.ecc.android.sdk.internal.jni.RustBackend$Companion.access$createToAddress(RustBackend.kt:369)
	at cash.z.ecc.android.sdk.internal.jni.RustBackend$createToAddress$2.invokeSuspend(RustBackend.kt:303)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
```

Here are a few more hints:
- reproducible on the Testnet
- with SbS sync in progress
- old/new wallet makes no difference

**Comment by nuttycom** [comment]
This should be fixed by #894; @HonzaR please confirm now that it has been merged.

**Comment by nuttycom** [comment]
@LukasKorba reports that this error is still occurring in the IOS wallet.

**Comment by nuttycom** [comment]
Additional triage: 

Database state:
```
sqlite> select id_note, tx, block, output_index, value, is_change, spent from sapling_received_notes JOIN transactions on tx = id_tx;
1|1|2176960|1|1000000000|0|4
2|2|2177894|0|10681694|0|4
3|3|2178252|0|16521749|1|5
4|4|2179048|0|10680694|1|
5|5||0|16511749|1|
sqlite> select shard_index, subtree_end_height from sapling_tree_shards;
0|490074
1|
sqlite> select min(height), max(height) from blocks;
2170000|2183409
sqlite> select * from scan_queue ;
280000|490074|0
490074|2170000|50
2170000|2179110|10
... contiguous 10-block ranges elided here ...
2183310|2183410|10
2183410|2489003|50
```
Notes:
* This wallet was created prior to the introduction of account birthdays, so a lot has changed in librustzcash since the last report of this error. The `birthday_height` and `recover_until_height` columns are absent from the `accounts` table.
* This wallet was initialized with a birthday height of 2170000. All received notes are above that height.
* The scan queue prioritizes the range prior to the birthday height, 490074..2170000 at `ChainTip` priority. If a bug existed in the note selection query that caused notes in the second subtree to be selected without complete witness information available, it would explain this behavior.
* After #907 the 490074.2170000 range should be prioritized as `Ignore` as it is prior to the wallet birthday and it should no longer be necessary to scan this range to construct witnesses. 
* Given the changes in #907, it is likely that the conditions that permitted this bug to appear no longer apply, given the new approach to account birthday initialization and the related changes to note selection.

**Comment by nuttycom** [comment]
So much has changed that directly affects the conditions of this bug that I'm going to mark it closed for now, and then if it recurs we'll reopen this and figure out how I was wrong.
