### ISSUE TITLE
zcash_client_backend: Improve reporting of wallet balance to account for fast spendability.

### ISSUE THREAD

**Issue by nuttycom** [zcash/librustzcash#900]
The current wallet balance APIs may return incorrect or misleading information, because prior to a full scan being complete the wallet balance is not fully confirmed, as spends made using another wallet with the same seed may not be discovered until historic scanning is performed. As such, we need to more accurately represent the following for wallet balance:

* Max potentially spendable value
* Pending potentially spendable value (notes detected but witness information is incomplete or insufficient confirmations to spend)
* Whether or not this potentially spendable value has been confirmed (wallet is fully scanned). This last bit of information is best determined directly from the wallet sync state, which should be understood in terms of the percentage of total note commitments that have been scanned.

**Comment by nuttycom** [comment]
Related to #865

**Comment by str4d** [comment]
@nuttycom and I worked out how balances should be grouped within the state space of notes:

![Imagepipe_1.jpg](https://github.com/zcash/librustzcash/assets/4993799/47bb14be-34e0-4393-a320-5adb948e107a)

The three directions are state transitions for a note:
- `nf` - we determine that a note nullifier does not appear in the chain, and the note is unspent.
- `w`: we build a complete witness to the desired anchor.
- `sec`: the note has sufficient confirmations to be safely spendable.

Currently the `nf` transition only happens when we are fully scanned to the chain tip. Then then a block arrives, we drop down to the lower plane until we've scanned it, and then we jump back up.

So we can currently represent the wallet balances with two states as we currently do:
- Confirmed
- Pending

And then whether or not those balances are optimistic is just a boolean indicating whether we are fully synced.

Once we move to DAGSync we will be able to occupy all four state spaces, but we don't need to expose that yet.

**Comment by zookozcash** [comment]
For the Zashi UI, we need to tell the user which unspendable ("pending") ZEC is due to change coming back to them and which is due to incoming money that is not yet available.

**Comment by nuttycom** [comment]
Tentative design to satisfy @zookozcash's requirement: https://github.com/zcash/librustzcash/pull/914/commits/d774275a2057c4dfad4a8b3cf83bc155a2639c7a#diff-7f82231afa857f8e7562f9184e551564997e1f74aaad9c6ba17e348fc89abeadR50-R54

**Comment by str4d** [comment]
> For the Zashi UI, we need to tell the user which unspendable ("pending") ZEC is due to change coming back to them and which is due to incoming money that is not yet available.

@zookozcash That is encoded in the "security" axis of the diagram above. Notes received as change can have a shorter confirmation window (as you trust the sender - yourself), and transition sooner to the "confirmed" state than notes received from external users. We might want to expose in the Zashi UI "how soon are different subgroups of the pending balance likely to become spendable".

**Comment by nuttycom** [comment]
Also related to #873 - the fix for this issue should also address that.
