### ISSUE TITLE
Error tx-expiring-soon

### ISSUE THREAD

**Issue by LukasKorba** [zcash/librustzcash#906]
This happened before but with much lower height being set. Now both heights are closer together but still the transaction failed to send.

This happened with the wallet I received an error `18: bad-txns-sapling-duplicate-nullifier` so I decided to fully sync before send. In the end I tried two more sends at around 70% and 90%, both ended up with this expiry height errors. After I successfully finished SbS sync, the transaction succeeded.

Question basically is if expiry height is an error in general or somewhat related to this wallet that needs to be fully synced before send.

```
▿ ZcashError
 ▿ unknown : TransactionEncoderError
  ▿ submitError : 2 elements
   - code : -26
   - message : “tx-expiring-soon: expiryheight is 2478263 but should be at least 2478334 to avoid transaction expiring soon”
```

**Comment by nuttycom** [comment]
After discussing on a call, what we believe to be happening here is that `update_chain_tip` is not being called intermittently during the process of recovering from seed. Since the recovery takes a few hours, the chain tip moves far enough that transactions created relative to the chain tip at the time of the `update_chain_tip` call will be close to expiring or have expired before the sync completes. The solution is simply to periodically interrupt wallet recovery, say every 5 or 10 minutes, call `update_chain_tip` and then `request_scan_ranges` and process the newly retrieved scan ranges in priority order.

**Comment by LukasKorba** [comment]
After the day of manual testing, this bug has no longer appeared. Previously it was possible to reproduce it easily so I believe it's fixed, closing.

The solution was to call update chain tip every 10mins and 'restart' the scanning with suggest scan ranges call.
