### ISSUE TITLE
get_wallet_summary is inconsistent about including funds from mempool txns that can still be mined when min_confirmations == 0

### ISSUE THREAD

**Issue by daira** [zcash/librustzcash#940]
@str4d wrote at https://github.com/zcash/librustzcash/pull/914/files#r1316507311 :
> There is a slight issue here regarding notes that are just about to expire. Without the `max(_, 1)`, with `min_confirmations == 0` this would set `summary_height` to the "mempool height" (`chain_height + 1`), which is precisely what we want for any transaction in the mempool (that still has a chance of being mined, and thus mined before expiry). Down below in the note selection code, we exclude transactions that have expired as of `summary_height` (because `expiry_height < summary_height`) from the balance, which means if someone calls this API with `min_confirmations == 0`, then about-to-expire funds will disappear from the wallet balance, only to reappear again if the transaction does actually get mined in the last block it can.
> 
> I'm fine with this being an edge case we don't handle yet, and instead merging @daira's suggested comment change that we treat `min_confirmations == 0` as `min_confirmations == 1` for shielded notes.

**Comment by daira** [comment]
This is currently the only dependency of #960 (zcash_client_backend 0.10.1) in the DAG. Do we still need a zcash_client_backend 0.10.1 release for this, or can we fold it into 0.11.0?

**Comment by str4d** [comment]
@daira thinks we might have fixed this; we should check.

**Comment by nuttycom** [comment]
I just revisited this, and it looks like there isn't an actual inconsistency; it's just that `min_confirmations == 0` is not respected (it's always effectively set to have a floor of `1`). I think that in practice this isn't currently a problem, because we don't ever see transactions from the mempool (at least in our use of `zcash_client_sqlite`; I haven't analyzed what happens if someone uses `decrypt_and_store_transaction` with a tx retrieved from the mempool.) So at very least, this issue title is inaccurate. If we choose to begin supporting `min_confirmations == 0` then we'll need to revisit `get_wallet_summary` regardless (and write some tests that specifically target mempool transactions). So I think this is okay to close.

**Comment by str4d** [comment]
Closing per above.
